apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc
spec:
  generators:
  - list:
      elements:
      - env: test
  template:
    metadata:
      name: 'hello-app-{{env}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/OsheRicko/gitops-platform
          targetRevision: main
          path: initial-app
          helm:
            valueFiles:
            - values.yaml
            - $values/values.yaml
        - repoURL: https://github.com/OsheRicko/my-cool-app-repo
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: 'hello-app'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
